#!/bin/sh
# small examples

. "${srcdir=.}/init.sh"; path_prepend_ ../src

fail=0

cat <<EOF > exp- || fail=1
1c1
< a
---
> b
EOF

cat <<EOF > exp--u || fail=1
--- a
+++ b
@@ -1 +1 @@
-a
+b
EOF

cat <<EOF > exp--c || fail=1
*** a
--- b
***************
*** 1 ****
! a
--- 1 ----
! b
EOF

echo a > a
echo b > b
for opt in '' -u -c; do
  returns_ 1 diff $opt a b > out 2> err || fail=1
  # Remove date and time.
  sed -e 's/^\([-+*][-+*][-+*] [^	]*\)	.*/\1/' out > k; mv k out
  compare exp-$(echo $opt|tr ' ' _) out || fail=1
done

# This would overflow a signed integer in diffutils-3.12 and earlier.
returns_ 1 diff -u -9999999999999999999999999999 a b >out-t 2>err || fail=1
# Remove date and time.
sed -e 's/^\([-+*][-+*][-+*] [^	]*\)	.*/\1/' out-t >out || framework_failure_
cat <<\EOF >exp || framework_failure
--- a
+++ b
@@ -1 +1 @@
-a
+b
EOF
compare exp out || fail=1
compare /dev/null err || fail=1

Exit $fail
